name = "certi-website"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[pages]
# Next on Pages outputs to .vercel/output/static
pages_build_output_dir = ".vercel/output/static"
